In [1]:
import pandas as pd
import numpy as np

In [3]:
from sklearn import datasets

In [4]:
iris=datasets.load_iris()

In [5]:
X=iris.data

In [6]:
y=iris.target

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [13]:
X_train.shape

(112, 4)

In [14]:
X_test.shape

(38, 4)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc=StandardScaler()

In [17]:
X_train=sc.fit_transform(X_train)

In [18]:
X_train

array([[ 1.54399532e-02, -1.19254753e-01,  2.25126850e-01,
         3.55797625e-01],
       [-9.98450310e-02, -1.04039491e+00,  1.13559562e-01,
        -2.98410911e-02],
       [ 1.05300481e+00, -1.19254753e-01,  9.50314227e-01,
         1.12707506e+00],
       [-1.36797986e+00,  3.41315328e-01, -1.39259884e+00,
        -1.31530348e+00],
       [ 1.16828980e+00,  1.11030287e-01,  7.27179649e-01,
         1.38416753e+00],
       [-1.02212490e+00,  1.03217045e+00, -1.22524790e+00,
        -8.01118523e-01],
       [-5.60984968e-01,  1.49274053e+00, -1.28103155e+00,
        -1.31530348e+00],
       [-1.02212490e+00, -2.42210516e+00, -1.65358660e-01,
        -2.86933568e-01],
       [ 7.07149859e-01, -1.19254753e-01,  9.50314227e-01,
         7.41436341e-01],
       [ 9.37719827e-01,  5.71600368e-01,  1.06188152e+00,
         1.64126001e+00],
       [ 1.30724937e-01, -1.96153508e+00,  6.71396005e-01,
         3.55797625e-01],
       [ 9.37719827e-01, -1.27067995e+00,  1.11766516e+00,
      

In [19]:
X_test=sc.fit_transform(X_test)

In [20]:
X_test

array([[ 0.12564197, -0.62989827,  0.88070613,  1.81979323],
       [ 0.42404164, -2.01082908,  0.21500059, -0.1846167 ],
       [-0.32195754,  2.59227364, -1.35848522, -1.32999381],
       [ 2.36363949, -0.39974313,  1.60693035,  0.9607604 ],
       [-1.06795671,  0.75103255, -1.29796654, -1.32999381],
       [ 0.87164114,  0.52087741,  1.4253743 ,  1.96296536],
       [-1.06795671,  0.98118769, -1.41900391, -1.18682167],
       [ 1.46844048,  0.06056714,  0.63863139,  0.53124399],
       [ 1.61764032, -0.62989827,  0.69915007,  0.38807185],
       [ 0.57324147, -0.62989827,  0.21500059,  0.24489971],
       [ 0.57324147, -1.09020854,  1.18329955,  0.38807185],
       [ 1.02084098,  0.29072228,  0.51759402,  0.53124399],
       [ 0.57324147, -0.62989827,  0.63863139,  0.10172757],
       [ 1.17004081, -0.62989827,  0.5781127 ,  0.53124399],
       [ 0.57324147, -0.39974313,  0.63863139,  0.38807185],
       [-1.21715655,  1.21134282, -1.35848522, -1.47316594],
       [ 0.42404164, -0.

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
rf=RandomForestClassifier(random_state=0)

In [32]:
# Step5-- Training the Model
rf.fit(X_train,y_train)

RandomForestClassifier(random_state=0)

In [39]:
# predict data
y_pred=rf.predict(X_test)

In [40]:
# Actual data y_test
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1])

In [41]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [42]:
print("Accuracy --",accuracy_score(y_test,y_pred))

Accuracy -- 0.9473684210526315


# Confusion Matric

In [1]:
cf.cinfusion_matrix(y_test,y_pres)

NameError: name 'cf' is not defined