In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('C:\\Users\\shamoo\\Salary_Data.csv')

In [3]:
dataset.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [8]:
# dividing dataset into x and y
X=dataset.iloc[:,1:2].values

In [15]:
X.shape

(30, 1)

In [121]:
y=dataset['Salary'].values

In [122]:
y.shape

(30,)

In [123]:
# dividing data into  test and trainn
from sklearn.model_selection import train_test_split

In [124]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [125]:
X_train

array([[ 1.3590738 ],
       [-0.74976858],
       [ 0.26285865],
       [ 0.93861127],
       [-0.71830716],
       [-0.37004264],
       [-0.42881019],
       [-0.55250402],
       [ 1.40274136],
       [ 0.58377993],
       [-1.10552744],
       [ 1.70177321],
       [-0.58815781],
       [-1.33978143],
       [ 0.19885989],
       [ 0.66547573],
       [-0.69801306],
       [-0.79981746],
       [ 1.09740238],
       [-1.20495739],
       [-1.36011263],
       [ 0.82623317],
       [-0.29921736],
       [-0.70662043]])

In [126]:
y_train

array([112635.,  55794.,  83088., 101302.,  56642.,  66029.,  64445.,
        61111., 113812.,  91738.,  46205., 121872.,  60150.,  39891.,
        81363.,  93940.,  57189.,  54445., 105582.,  43525.,  39343.,
        98273.,  67938.,  56957.])

In [127]:
# Scaling down value
from sklearn.preprocessing import StandardScaler

In [128]:
sc=StandardScaler()

In [129]:
sc_X=StandardScaler()

In [130]:
sc_Y=StandardScaler()

In [131]:
X=sc_X.fit_transform(X)

In [132]:
y=sc_Y.fit_transform(y.reshape(-1,1))

In [133]:
X

array([[-1.36011263],
       [-1.10552744],
       [-1.419919  ],
       [-1.20495739],
       [-1.33978143],
       [-0.71830716],
       [-0.58815781],
       [-0.79981746],
       [-0.42881019],
       [-0.69801306],
       [-0.47433279],
       [-0.74976858],
       [-0.70662043],
       [-0.70201994],
       [-0.55250402],
       [-0.29921736],
       [-0.37004264],
       [ 0.26285865],
       [ 0.19885989],
       [ 0.66547573],
       [ 0.58377993],
       [ 0.82623317],
       [ 0.93861127],
       [ 1.40274136],
       [ 1.24020308],
       [ 1.09740238],
       [ 1.51986835],
       [ 1.3590738 ],
       [ 1.72102849],
       [ 1.70177321]])

In [134]:
y

array([[-1.36011263],
       [-1.10552744],
       [-1.419919  ],
       [-1.20495739],
       [-1.33978143],
       [-0.71830716],
       [-0.58815781],
       [-0.79981746],
       [-0.42881019],
       [-0.69801306],
       [-0.47433279],
       [-0.74976858],
       [-0.70662043],
       [-0.70201994],
       [-0.55250402],
       [-0.29921736],
       [-0.37004264],
       [ 0.26285865],
       [ 0.19885989],
       [ 0.66547573],
       [ 0.58377993],
       [ 0.82623317],
       [ 0.93861127],
       [ 1.40274136],
       [ 1.24020308],
       [ 1.09740238],
       [ 1.51986835],
       [ 1.3590738 ],
       [ 1.72102849],
       [ 1.70177321]])

In [135]:
# Now we apply Support Vectors Regressor

In [136]:
from sklearn.svm import SVR

In [137]:
rg=SVR(kernel='rbf')

In [147]:
rg.fit(X,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

In [156]:
X.predict([[5]])  ////errore

AttributeError: 'numpy.ndarray' object has no attribute 'predict'