In [10]:
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import numpy as np




In [18]:
n_samples,n_features=10,5

In [19]:
r=np.random.RandomState(0)

In [20]:
y=r.random(n_samples)

In [21]:
x=r.rand(n_samples,n_features)

In [22]:
x

array([[0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077],
       [0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676],
       [0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559]])

In [23]:
y

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [28]:
model=make_pipeline(StandardScaler(),SVR())

In [29]:
# model creation

model.fit(x,y)

Pipeline(steps=[('standardscaler', StandardScaler()), ('svr', SVR())])

In [30]:
model.predict(x)

array([0.64879053, 0.61523551, 0.65498007, 0.64437647, 0.52393096,
       0.61324905, 0.53763336, 0.79189557, 0.86338583, 0.48375711])